version: '3'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - lesser-net

  backend:
    build:
      context: ./backend
    networks:
      - lesser-net

  frontend:
    build:
      context: ./frontend
    networks:
      - lesser-net

networks:
  lesser-net:
    external: true