version: '3'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - lesser-net

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      - lesser-net

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    networks:
      - lesser-net

networks:
  lesser-net:
    driver: bridge