version: “3”

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - certbot-www:/var/www/certbot/:ro
      - certbot-conf:/etc/nginx/ssl/:ro
    networks:
      - lesser-net

  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRETS=${GITHUB_CLIENT_SECRETS}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - lesser-net

  frontend:
    build:
      context: ./frontend
    networks:
      - lesser-net

networks:
  lesser-net:
    external: true

volumes:
  certbot-www:
    external: true
  certbot-conf:
    external: true
