version: '3'

services:
  mysql:
    env_file:
      - .env
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
    external: true

networks:
  lesser-net:
    external: true
