const LOGIN_LENGTH = {
  HEIGHT: 700,
  WIDTH: 758,
};

const SCRIPTBAR_POS = {
  LEN1: 35,
  LEN2: 50,
};

const HORIZON_SCRIPT_POS = {
  TOP: SCRIPTBAR_POS.LEN2,
  LEFT: SCRIPTBAR_POS.LEN1,
};

const VERTICAL_SCRIPT_POS = {
  TOP: SCRIPTBAR_POS.LEN1,
  LEFT: SCRIPTBAR_POS.LEN2,
};

const TYPING_ANIME_FRAME = 50;

export { LOGIN_LENGTH, HORIZON_SCRIPT_POS, VERTICAL_SCRIPT_POS, TYPING_ANIME_FRAME };
