name: Dev Server Backend/Frontend CD

run-name: ${{ github.actor }} is deploying DevServer

on: 
  pull_request:
    paths:
      - 'backend/**'
      - 'frontend/**'
    types:
     - closed
    branches:
      - dev

jobs:
  dev_deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Filter Backend/Frontend
      uses: dorny/paths-filter@v2.11.1
      id: changes
      with:
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: DevServer Backend CD
      env:
        SSH_DEV_DEVELOPER_PASSWORD: ${{ secrets.SSH_DEV_DEVELOPER_PASSWORD }}
        DEV_MYSQL_USER: ${{ secrets.DEV_MYSQL_USER }}
        DEV_MYSQL_PASSWORD: ${{ secrets.DEV_MYSQL_PASSWORD }}
        DEV_MYSQL_DATABASE: ${{ secrets.DEV_MYSQL_DATABASE }}
      run: |
        sshpass -p $SSH_DEV_DEVELOPER_PASSWORD ssh -o "StrictHostKeyChecking=no" developer@dev.lesser-project.site "cd /home/developer/web10-Lesser && git pull && DEV_MYSQL_USER=$DEV_MYSQL_USER DEV_MYSQL_PASSWORD=$DEV_MYSQL_PASSWORD DEV_MYSQL_DATABASE=$DEV_MYSQL_DATABASE docker compose -f docker-compose.dev.yml up -d --build backend"

    - name: DevServer frontend CD
      env:
        SSH_DEV_DEVELOPER_PASSWORD: ${{ secrets.SSH_DEV_DEVELOPER_PASSWORD }}
      run: |
        sshpass -p $SSH_DEV_DEVELOPER_PASSWORD ssh -o "StrictHostKeyChecking=no" developer@dev.lesser-project.site "cd /home/developer/web10-Lesser && git pull && docker compose -f docker-compose.dev.yml up -d --build frontend"