name: Production Server Backend/Frontend CD

run-name: ${{ github.actor }} is deploying Production Server

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  get-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Get Release Notes
        run: |
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          echo "Release Name: ${{ github.event.release.name }}"
          echo "Release Notes: ${{ github.event.release.body }}"
