const GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID';
const GITHUB_CLIENT_SECRETS = 'GITHUB_CLIENT_SECRETS';
const DATABASE_HOST = 'DATABASE_HOST';
const DATABASE_PORT = 'DATABASE_PORT';
const DATABASE_USER = 'DATABASE_USER';
const DATABASE_PASSWORD = 'DATABASE_PASSWORD';
const DATABASE_NAME = 'DATABASE_NAME';

export {
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRETS,
  DATABASE_HOST,
  DATABASE_PORT,
  DATABASE_USER,
  DATABASE_PASSWORD,
  DATABASE_NAME,
};
